# Generated by Django 5.2.11 on 2026-02-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_reservered',
            field=models.BooleanField(default=False),
        ),
    ]
