# Generated by Django 5.2.11 on 2026-02-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_table_is_reservered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='is_reservered',
            new_name='is_reserved',
        ),
    ]
